/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndk_dome_Hello */

#ifndef _Included_com_ndk_dome_Hello
#define _Included_com_ndk_dome_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndk_dome_Hello
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ndk_dome_Hello_getString
  (JNIEnv *, jclass);

/*
 * Class:     com_ndk_dome_Hello
 * Method:    jniShowLog
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ndk_dome_Hello_jniShowLog
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ndk_dome_Hello
 * Method:    fun
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ndk_dome_Hello_fun
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
